In [9]:
import numpy as np
from math import sin, cos

#Lattice parameter values, which are calculated in Angstroms
#Ru represents Ruthenium, Sa represents Sapphire
aRu = 2.7059
cRu = 4.2819
cSa = 12.992
aSa = 4.75932

#Sapphire is hexagonal-rhombohedral which means it is trigonal.
#Calculate the metric tensor, using the lattice parameters.
mhRu = np.array([[(aRu)**2, -((aRu)**2)/2, 0],[-((aRu)**2)/2, (aRu)**2, 0],[0,0,(cRu)**2]])
mhSa = np.array([[(aSa)**2, -((aSa)**2)/2, 0],[-((aSa)**2)/2, (aSa)**2, 0],[0,0,(cSa)**2]])
print(mhRu, '\n')
print(mhSa, '\n')

#Calculate the reciprocal metric tensor, using the lattice parameters.
rhRu = np.array([[4/(3*(aRu)**2), 2/(3*(aRu)**2), 0],[ 2/(3*(aRu)**2), 4/(3*(aRu)**2), 0],[0,0,1/((cRu)**2)]])
rhSa = np.array([[4/(3*(aSa)**2), 2/(3*(aSa)**2), 0],[ 2/(3*(aSa)**2), 4/(3*(aSa)**2), 0],[0,0,1/((cSa)**2)]])
print(rhRu, '\n')
print(rhSa, '\n')

print("Question 3, the misfit strain for the hexagon-on-hexagon OR =",((aSa-aRu)/aRu)*100, "%", '\n')
#cartesian will be new.

hklRu = np.array([[1,0,0]])
hklRuT = np.transpose(hklRu)

hklSa = np.array([[1,1,0]])
hklSaT = np.transpose(hklSa)

gSa = np.dot(np.dot(hklSa,rhSa),hklSaT)
dSa = 1/(np.sqrt(gSa))
#print(gSa)

gRu = np.dot(np.dot(hklRu,rhRu),hklRuT)
dRu = 1/(np.sqrt(gRu))
# print(gRu)

#CCalculate the  misfit strain for the rotated honeycomb OR. 
em = (dSa - dRu)/dRu
print("Question 4, the  misfit strain for the rotated honeycomb OR = ", float(em*100), "%", '\n')

#Compute the resolved shear stress

#Sample Frame - Old Frame
#define 3 perpendicular basis vectors for the Cartesian axes
a = np.array([[1,0,0]])
c = np.array([[0,0,1]])
#b is obtained from the cross product of a and b, to obtain a perpendicular direction.
b = np.array([[1,2,0]])

#find the magnitude of each of the vector
def magnitude(f,g):
    #where f is the vector and g is the metric tensor
    #multiply the i vector by the metric tensor
    return1 = np.matmul(f,g)
    #multiply the result with the transpose of the provided i vector
    return2 = np.dot(return1.flatten(), np.transpose(f.flatten()))
    #To obtain the magnitude, find the square root of the scalar product.
    return np.sqrt(return2)

am = magnitude(a,mhRu)
bm = magnitude(b,mhRu)
cm = magnitude(c,mhRu)

#Normalise the vector by dividing the miller indice matrix with the magnitude of the vector.
an = a/am
bn = b/bm
cn = c/cm

#create the 3x3 sample matrix by stacking the a,b,c vectors vertically.
sample = np.vstack((an,bn,cn))
print("sample", '\n',sample, '\n')

#Remember to convert from reciprocal basis vectors to direct basis vectors

#Table 1
#Slip Frame - New Frame

#direction 1 is the normal to the slip plane.
z1 = np.matmul(np.array([[2,-1,1]]),rhRu) #value is in reciprocal space, 
#so we multiply by reciprocal metric tensor

x1 = np.array([[1,1,-1]])
#the a+b value is the cross product of the a and b directions.
#This would be in the reciprocal space, so multiply by reciprocal vector 
# to get the direct space value.
y1 = np.dot((np.array(np.cross(z1,x1))),rhRu)

#find the magnitude of each vector
x1m = magnitude(x1,mhRu)
y1m = magnitude(y1,mhRu)
z1m = magnitude(z1,mhRu)

#normalise each vector
x1n = x1/x1m
y1n = y1/y1m
z1n = z1/z1m

#create the 3x3 slip matrix by stacking the a,b,c vectors vertically.
slip1 = np.vstack((x1n,y1n,z1n))
print("slip",'\n', slip1, '\n')

#find the transformation matrix, which is based on the rotation matrix
#create a function that does this.
#cos theta = (a*mhRu*x)/(magnitude a)*(magnitude b)    

[[ 7.32189481 -3.66094741  0.        ]
 [-3.66094741  7.32189481  0.        ]
 [ 0.          0.         18.33466761]] 

[[ 22.65112686 -11.32556343   0.        ]
 [-11.32556343  22.65112686   0.        ]
 [  0.           0.         168.792064  ]] 

[[0.18210222 0.09105111 0.        ]
 [0.09105111 0.18210222 0.        ]
 [0.         0.         0.05454149]] 

[[0.05886389 0.02943194 0.        ]
 [0.02943194 0.05886389 0.        ]
 [0.         0.         0.00592445]] 

Question 3, the misfit strain for the hexagon-on-hexagon OR = 75.88676595587418 % 

Question 4, the  misfit strain for the rotated honeycomb OR =  1.5482716715166647 % 

sample 
 [[0.36956281 0.         0.        ]
 [0.21336719 0.42673437 0.        ]
 [0.         0.         0.23354118]] 

slip 
 [[ 0.19742437  0.19742437 -0.19742437]
 [ 0.13764739  0.37831976  0.10302497]
 [ 0.35239046  0.          0.07036304]] 



In [10]:
#function that produces the cosine of the input miller indices
def cosine(p,q):
    #multiply basis vector by the slip vector
    #obtain the magnitude of each of the input vectors
    pm = magnitude(p,mhRu)
    qm = magnitude(q,mhRu)
    #find the dot product of the sample frame and the Ruthenium metric tensor
    cos1 = np.dot(q,mhRu)
    #find the dot product of previous dot product and the transpose of slip frame
    cos2 = np.dot(cos1,np.transpose(p))
    #find the multiplication of the magnitudes of both the sample and slip directions input.
    cos3 = qm*pm
    #find the cosine of the input values using the equation
    # cos theta = (p*mhRu*q)/((magnitude p)*(magnitude q))  
    return cos2/cos3

#sequence for transformation matrix is new.old = slip.sample
#Find the vector cosines created from the dot product of each point on the rotation 
# matrix.
st1 = np.hstack((cosine(a,x1),cosine(b,x1),cosine(c,x1)))
st2 = np.hstack((cosine(a,y1),cosine(b,y1),cosine(c,y1)))
st3 = np.hstack((cosine(a,z1),cosine(b,z1),cosine(c,z1)))

#create the 3x3 transformation matrix by stacking the a,b,c vectors vertically.
st = np.vstack([st1,st2,st3])
print("transformation cosine matrix",'\n', st, '\n', st.shape,'\n')

#define the normal biaxial stress tensor
stress = np.array([[10, 0, 0],
                    [0, 10, 0],
                    [0, 0, 0]])
#measured in Gigapascals

#find the resolved shear stress of the slip system by obtaining dot product of 
# the stress matrix when multiplied with the normal stress tensor
rss1 = np.dot(stress,np.transpose(st))
rss = np.dot(st,rss1)

print("Resolved shear stress on the slip systems listed in Table 1," ,'\n',rss,'\n')


transformation cosine matrix 
 [[ 0.2671053   0.46263996 -0.84535142]
 [-0.13938764  0.88654626  0.44114263]
 [ 0.95353335  0.          0.3012875 ]] 
 (3, 3) 

Resolved shear stress on the slip systems listed in Table 1, 
 [[ 2.85380975  3.72920548  2.54693815]
 [ 3.72920548  8.05393182 -1.32910759]
 [ 2.54693815 -1.32910759  9.09225843]] 



In [11]:
#create a function that calculates the resolved stress for
#stresses with the same sample frame, slip directions and 
# different direction 1 valuess normal to the slip planes.
#Remember to insert values as miller indices

def slipstress(k,l,j):
    #direction 1 is the normal to the slip plane.
    z2 = np.matmul(np.array([[k,l,j]]),rhRu) 
    #value is in reciprocal space, so we multiply by reciprocal metric tensor
    x2 = np.array([[1,1,-1]])
    #the a+b value is the cross product of the a and b directions.
    #This would be in the reciprocal space, so multiply by reciprocal 
    # vector to get the direct space value.
    y2 = np.dot((np.array(np.cross(z2,x2))),rhRu)

    #find the magnitude of each vector
    x2m = magnitude(x2,mhRu)
    #confirm the magnitude function works
    # print(x2m)
    y2m = magnitude(y2,mhRu)
    z2m = magnitude(z2,mhRu)

    #normalise each vector
    x2n = x2/x2m
    y2n = y2/y2m
    z2n = z2/z2m

    #create the 3x3 slip matrix by stacking the a,b,c vectors vertically.
    slip2 = np.vstack((x2n,y2n,z2n))
    #print("slip",'\n', slip2, '\n')
    
    #find the cosine of each position in the rotation matrix by 
    # finding the cosine between the slip frame and sample frame.
    #sequence for transformation matrix is new.old = slip.sample
    st1n = np.hstack((cosine(a,x2),cosine(b,x2),cosine(c,x2)))
    st2n = np.hstack((cosine(a,y2),cosine(b,y2),cosine(c,y2)))
    st3n = np.hstack((cosine(a,z2),cosine(b,z2),cosine(c,z2)))
    
    #create the 3x3 transformation matrix by stacking the a,b,c vectors vertically.
    stn = np.vstack([st1n,st2n,st3n])
    #print("transformation cosine matrix",'\n', stn,'\n')
    
    #find the resolved shear stress of the slip system by obtaining dot product of the stress 
    # matrix when multiplied with the normal stress tensor
    rss1n = np.dot(stress,np.transpose(stn))
    rssn = np.dot(stn,rss1n)
    return print(rssn)
    
print("Question 5b, Table 1, Line 2 = 4.1", '\n', slipstress(0,1,1),'\n')

print("Question 5c, Table 1, Line 3 = 4.5", '\n', slipstress(1,1,2), '\n')




[[ 2.85380975 -1.98075127  4.05838537]
 [-1.98075127  9.45098361  1.12488637]
 [ 4.05838537  1.12488637  7.69520664]]
Question 5b, Table 1, Line 2 = 4.1 
 None 

[[2.85380975e+00 0.00000000e+00 4.51595698e+00]
 [4.44089210e-16 1.00000000e+01 1.33226763e-15]
 [4.51595698e+00 0.00000000e+00 7.14619025e+00]]
Question 5c, Table 1, Line 3 = 4.5 
 None 



In [12]:
#Question 6, Twinning Systems K with Twinning Planes n
#hkl are the inserted plane values
#uvw are the inserted direction values
def twin(h,k,l,u,v,w):
    #direction 1 is the normal to the slip plane.
    z2 = np.matmul(np.array([[h,k,l]]),rhRu) #value is in reciprocal space, 
    #so we multiply by reciprocal metric tensor
    x2 = np.array([[u,v,w]])
    #the a+b value is the cross product of the a and b directions.
    #This would be in the reciprocal space, so multiply by reciprocal vector to get the direct space value.
    y2 = np.dot((np.array(np.cross(z2,x2))),rhRu)

    #find the magnitude of each vector
    x2m = magnitude(x2,mhRu)
    #confirm the magnitude function works
    print(x2m)
    y2m = magnitude(y2,mhRu)
    z2m = magnitude(z2,mhRu)

    #normalise each vector
    x2n = x2/x2m
    y2n = y2/y2m
    z2n = z2/z2m

    #create the 3x3 slip matrix by stacking the a,b,c vectors vertically.
    slip2 = np.vstack((x2n,y2n,z2n))
    #print("slip",'\n', slip2, '\n')
    
    #find the cosine of each position in the rotation matrix by finding the cosine between the 
    # slip frame and sample frame.
    #sequence for transformation matrix is new.old = slip.sample
    st1n = np.hstack((cosine(a,x2),cosine(b,x2),cosine(c,x2)))
    st2n = np.hstack((cosine(a,y2),cosine(b,y2),cosine(c,y2)))
    st3n = np.hstack((cosine(a,z2),cosine(b,z2),cosine(c,z2)))
    
    #create the 3x3 transformation matrix by stacking the a,b,c vectors vertically.
    stn = np.vstack([st1n,st2n,st3n])
    #print("transformation cosine matrix",'\n', stn,'\n')
    
    #find the resolved shear stress of the slip system by obtaining dot product of the 
    # stress matrix when multiplied with the normal stress tensor
    rss1n = np.dot(stress,np.transpose(stn))
    rssn = np.dot(stn,rss1n)
    return print(rssn)

#create a function that converts values from the miller bravais to miller indices and convert to lists.
def direction(u,v,t,w):
    un = (2*u)+v
    vn = (2*v)+u
    wn = w
    d1 = [un,vn,wn]
    return d1 

#input the miller bravais values for the twinning directions.
k1 = direction(2/3,-1/3,1/3,-3/3)
print(k1)
k2 = direction(1,0,-1,-2)
print(k2)
k3 = direction(1/3,1/3,-2/3,-6/3)
print(k3)

#run the code to confirm it works as expected.
print("Question 6, Table 2, 1st row = 4.6", twin(2,-1,2,k1[0],k1[1],k1[2]), '\n')
print("Question 6, Table 2, 2nd row = 4.2", twin(1,0,1,k2[0],k2[1],k2[2]), '\n')
print("Question 6, Table 2, 4th row = 2.9", twin(1,1,1,k3[0],k3[1],k3[2]), '\n')

#The resolved shear stress for any other equation, with the same metric tensors can be obtained by 
#inputting the miller indices in the twin() function.
k4 = direction(-1,0,1,1) #convert miller bravais to miller indices.
print(k4)
print("Question 7, Table 2, 3rd row =", twin(1,0,2,k4[0],k4[1],k4[2]), '\n')


[1.0, 0.0, -1.0]
[2, 1, -2]
[1.0, 1.0, -2.0]
5.06523073709382
[[2.85380975e+00 2.10607447e-16 4.51595698e+00]
 [2.10607447e-16 1.00000000e+01 3.33271750e-16]
 [4.51595698e+00 3.33271750e-16 7.14619025e+00]]
Question 6, Table 2, 1st row = 4.6 None 

9.762394935158074
[[2.30479336e+00 4.44089210e-16 4.21139658e+00]
 [4.44089210e-16 1.00000000e+01 8.88178420e-16]
 [4.21139658e+00 8.88178420e-16 7.69520664e+00]]
Question 6, Table 2, 2nd row = 4.2 None 

8.981122716565007
[[9.07741570e-01 2.22044605e-16 2.87287677e+00]
 [2.22044605e-16 1.00000000e+01 0.00000000e+00]
 [2.87287677e+00 0.00000000e+00 9.09225843e+00]]
Question 6, Table 2, 4th row = 2.9 None 

[-2, -1, 1]
6.348255826603084
[[ 5.45049443e+00  0.00000000e+00 -4.97966412e+00]
 [-4.44089210e-16  1.00000000e+01  0.00000000e+00]
 [-4.97966412e+00 -4.44089210e-16  4.54950557e+00]]
Question 7, Table 2, 3rd row = None 

